- app/config.rb
The `Pathname` class needs to be explicitly required in the app config, it seems to only be a problem
on AWS infrastructure.
```
irb(main):001:0> class Foo; Pathname.new("/foo"); end
NameError: uninitialized constant Foo::Pathname
from (irb):1:in `<class:Foo>'
from (irb):1
from /usr/bin/irb:12:in `<main>'
irb(main):002:0> require 'pathname'; class Foo; Pathname.new("/foo"); end
=> #<Pathname:/foo>
```
> Explicitly require pathname class

- Gemfile
- Gemfile.lock
- lib/govuk_nodes.rb
- spec/govuk_nodes_spec.rb
- spec/spec_helper.rb
We're hitting AWS (and perhaps other) request limits with this, so let's cache it.
If we need to put more effort in later we could convert this to exponential backoff using the "too many requests" exception we get from the AWS client.
https://trello.com/c/f8U7EfUh/427-make-the-new-cache-clearing-app-invalidate-cache-in-varnish
> Cache node requests for 5 minutes

- lib/govuk_nodes/carrenza_fetcher.rb
- spec/support/puppetdb_helper.rb
This is required to wind up with a string like the following encoded in the URL:
`["or", ["~", ["fact", "fqdn"], "^cache-\\d+\\."]]`
https://trello.com/c/f8U7EfUh/427-make-the-new-cache-clearing-app-invalidate-cache-in-varnish
> We really mean it when we say don't escape these characters

- app/processor.rb
- spec/processor_spec.rb
Some content items may be accessible from multiple routes, therefore just clearing the `base_path` is not sufficient.
[Trello Card](https://trello.com/c/9k1peA1F/434-make-the-new-cache-clearing-app-invalidate-cache-in-fastly)
> Clear the cache for routes and redirects

- app/processor.rb
- spec/processor_spec.rb
Errors were being raised which we suspect eventually killed the systemd service as the logs only contained entries coming from the clearer classes . 
```
respawn limit 5 20
```
Handling and logging them in the Processor class will help keep the service up.
I tested the theory on one of the integration backends where the problem was present, the service stayed up with the logging in place.
Also notifies `GovukError` of the issue so that it reaches Sentry.
> Log error messages when processing queue

- lib/tasks/cache.rake
This was not working before as the arguments don't get passed automatically.
> Make sure base_path is passed to the other tasks

- README.md
You don't need to run `bundle exec` because the `bin/cache_clearing_service` file does that already for you.
> Don't bundle exec running the app in the README

- app/processor.rb
- spec/processor_spec.rb
This prevents the other routes from not being cleared if one route earlier on in the list fails.
> Report errors individually

- app/services/purger.rb
- spec/purger_spec.rb
Fastly has the concept of a soft purge that sets the TTL of a page to 0, but doesn't actually remove the page from its cache. This means that if the frontend is down for whatever reason, it'll still be able to serve content from its caches.
https://docs.fastly.com/api/purge#soft_purge
> Purge pages softly

- bin/cache_clearing_service
Rather than running it as a child process. This is neater, and I'm
hoping it will help upstart manage this service better. Currently, I
think there are old rake processes left around when it's restarted.
> Change ./bin/cache_clearing_service to exec bundler

- app/processor.rb
Rather than purging each path one by one this spawns a thread for each path and runs it in parallel.
At the moment the process doesn't happen quick enough and the queue can back up.
In theory, this should improve processing speed by a factor of 2 on average (since a content item has at least two paths, its own base path and the `/api/content` variation) but we'll deploy it to see whether this improves the situation and if not look into further optimisations.
A potential for the future might be to look into more advances methods such as using [Typhoeus](https://github.com/typhoeus/typhoeus) to execute all the `PURGE` requests in parallel.
> Clear paths in parallel using threads

- app/processor.rb
This makes sure that the variable is captured correctly in the thread from the for loop.
> Pass path to thread explicitly

- .foreman
- Gemfile
- Gemfile.lock
- Procfile
- bin/cache_clearing_service
- bin/json_logger
- lib/tasks/message_queue.rake
This should provide faster processing of higher priority messages, and more granular scaling.
https://github.com/alphagov/govuk-puppet/pull/8547
https://trello.com/c/qBtWYsPC/717-speed-up-cache-clearing-service
Effect of publishing a new edition of `/government/news/december-deal-delivers-for-uk-fleet-and-fish-stocks` (read bottom to top):
> Run multiple consumers on different queues

- app/processor.rb
- spec/govuk_nodes_spec.rb
- spec/processor_spec.rb
- spec/spec_helper.rb
We're seeing the queue for cache-clearing-service back up quite significantly. Although we should fix this problem, it's worth adding code into cache-clearing-service to not bother clearing the cache of pages that were updated over an hour ago and therefore likely already have their cache cleared. This should prevent the backlog from growing excessively big.
> Only purge pages that were updated recently

- .foreman
From 7 to 3, as the load placed on Varnish from the Cache Clearing
Service is causing issues with processing normal requests.
> Reduce the number of low cache-clearing-service workers

- app/services/fastly_clearer.rb
- lib/tasks/cache.rake
- spec/fastly_clearer_spec.rb
When clearing assets we need to use a different hostname for clearing Fastly cache, so this allows a full URL to be provided for Fastly only.
This is not supported in the Varnish or Fastly & Varnish tasks because assets do not go through Varnish.
https://trello.com/c/RASJllyU/916-update-hmrc-paye-tools-cache-clearing-documentation
> Allow Fastly cache clearing for full URLs

- lib/tasks/cache.rake
These tasks are run manually, so just print the error out, as it's
often a invalid path.
> Don't report errors to Sentry from cache:* Rake tasks

- app/processor.rb
We're currently getting errors with nil paths. I'm not sure where
these nil paths are coming from, so avoid erroring by skipping the
path if it's nil, and also log the payload so we can investigate
further.
> Log issues with nil paths

- lib/tasks/cache.rake
The `cache:clear_fastly` rake task has a param named `:base_path_or_url`.  The arg that is passed on from the `cache:clear` task when both the varnish and fastly caches are to be cleared is called `:base_path`.
This means that the fastly task doesn't work at the moment when called as a dependency and fails with the [following error](https://deploy.blue.production.govuk.digital/job/run-rake-task/19810/console):
> clear_fastly: error: undefined method `start_with?' for nil:NilClass
I've changed the `cache:clear` task to invoke both subtasks directly. I considered changing the parameter name of the fastly task back to `:base_path`, but it's useful to be aware that you can pass a full URL into this task (as when clearing assets for example).
> Fix rake task dependencies

- Rakefile
RSPec is a development dependency and as such, we see errors outside
of the dev environment if this line is not wrapped in an exception
handler.
See:
https://github.com/alphagov/cache-clearing-service/pull/259\#pullrequestreview-372584676
> Wrap 'require "rspec/core/rake_task"' in begin/rescue/end block

- Rakefile
- lib/tasks/lint.rake
https://trello.com/c/5Gob6WUL/147-ensure-that-rubocop-runs-as-part-of-bundle-exec-rake-as-one-of-the-default-tasks
This adds a new 'lint' rake task that runs as part of a default call
to 'rake'. Having linting run locally by default makes it easier to
catch build issues, and is a prerequisite for moving to GitHub Actions,
since we want to avoid listing lots of separate build steps.
The 'lint' task runs RuboCop as a separate process, which is a technique
to avoid a LoadError when the gem is unavailable in production.
> Extend 'default' rake task with RuboCop linting

- Gemfile
- Gemfile.lock
These are the necessary changes for Ruby 2.7, tested against 2.7.1
Since there is an automated process for updating Ruby versions in govuk apps, I changed the version locally, made the necessary updates, but raised a PR with version 2.6.6. The tests will fail on Jenkins because of this.
The only significant change that has been made other than unpinning dependencies is to add the Thwait gem as this is no longer bundled after Ruby 2.7.0.
> Update to Ruby 2.7

- app/services/fastly_clearer.rb
- app/services/varnish_clearer.rb
- spec/fastly_clearer_spec.rb
- spec/varnish_clearer_spec.rb
The tests `fastly_clearer_spec.rb` and `varnish_clearer_spec.rb` were
using `expect_any_instance_of` to set expectations on private instance
variables. This is generally considered bad practice
(see https://github.com/rubocop/rspec-style-guide#any_instance_of).
This PR instead uses dependency injection to pass in a mock object,
and replaces an instance of `expect` in a `before` hook with
the functionally equivalent but more semantically correct `allow`.
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️
> Remove `expect_any_instance_of`in tests

- app/services/fastly_clearer.rb
- app/services/purger.rb
- app/services/varnish_clearer.rb
- spec/fastly_clearer_spec.rb
- spec/varnish_clearer_spec.rb
We've decided to implement account navigation on GOV.UK by
implementing a custom request header, which is set by Fastly if a
session cookie is present (and unset otherwise).  See [1].
So, since every page will potentially have two variants cached (when
we implement the new navigation), we will need the
cache-clearing-service to handle both of them.
For Fastly, set a session cookie; the `vcl_recv` method will then
produce the `GOVUK-Account-Session-Exists` header which the caching
uses.  For Varnish, set the `GOVUK-Account-Session-Exists` header
directly, as that assumes the request has come via Fastly.
I also changed the logger to print out the extra headers, if set, so
we'll see log entries like:
Purging: https://www.gov.uk
Purging: https://www.gov.uk …
> Clear the cache both with and without a GOV.UK account session

- Gemfile
- Gemfile.lock
This has been the default for new Gemfiles since a major security incident at rubygems.org in 2013[[1]].
[1]: https://venturebeat.com/business/rubygems-org-hacked-interrupting-heroku-services-and-putting-millions-of-sites-using-rails-at-risk/
> Use TLS when fetching gem dependencies.

- .dockerignore
- Dockerfile
- app/config.rb
Also fix logging so that the app can run in a container without trying to create files under its own source directory.
Tested: successfully built locally (`docker build -t cache-clearing-service .`) and [on GitHub Actions](https://github.com/alphagov/cache-clearing-service/actions/runs/3686440067).
> Add Dockerfile for container image build.

- lib/govuk_nodes/aws_fetcher.rb
- spec/govuk_nodes/aws_fetcher_spec.rb
- spec/govuk_nodes_spec.rb
This is env is un-needed as we no longer need to distigush between AWS and Carrenza (we don't use Carrenza anymore). We also don't need to filter EC2 instances by stackname, we never implemented blue/green deployments (and have no plans too). Our current instances all have the same stackname "blue".
> Remove use AWS_STACKNAME env var

- .github/workflows/ci.yml
- .github/workflows/rspec.yml
This is in preparation for the Replatforming launch, shortly after which we'll turn off CI on Jenkins for apps which have moved to Kubernetes (which are almost all apps, including cache-clearing-service).
No functional change and no effect on EC2 builds/deployments.
Tested: new pre-merge checks ran against this PR; see below.
> Run tests on GitHub Actions.
